apiVersion: v2
name: onecx-db-check
version: 0.0.0
appVersion: 0.0.0
description: OneCX database check
keywords:
  - database
sources:
  - https://github.com/onecx/onecx-db-check
maintainers:
  - name: tkit developer
    email: tkit_dev@1000kit.org
dependencies:
  - name: helm-quarkus-app
    alias: app
    version: 0.40.0
    repository: oci://ghcr.io/onecx/charts